language: ruby
rvm:
  - 2.0.0-p247
before_script:
  - psql -c 'create database test;' -U postgres
script: bundle exec rspec spec
env:
  global:
    DATABASE_URL: "postgres://postgresql:@localhost/test"
    secure: fXmk/Jyrh4yzyU7h98V8eJ4+QXptS4izW8sf1SoK5Fz+JUj4g/Befp/V4QswRyZc1C5nwUCCcVjAGaNdX1WbCZKHhyT23fjKLX413YtShadzcu42Ok+BG1aLONI6O3gm61VlhywgCftfht8if+r1EXjA6dtU2tAc5pgSyLyfsyM=
