language: ruby
cache: bundler
rvm:
  - 2.0.0-p247
env:
  - DATABASE_URL=postgres://postgres:@127.0.0.1/shareit_test
before_script:
  - psql -c 'create database shareit_test;' -U postgres
script: RAILS_ENV=test bundle exec rake db:migrate && bundle exec rspec spec
