connection: &connection
  username: ombr
  password: root
  adapter: postgresql
  encoding: utf8
  host: localhost

development:
  database: blog
  <<: *connection

test: &test
  database: blog-test
  <<: *connection

cucumber:
  <<: *test
